#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -e

echo 1>&2
echo "Setting environment variables..." 1>&2

export CI_ENV="${APPLICATION_ENV:-production}"
if [ "$(type -t set_env_var)" == "function" ]; then
  set_env_var 'CI_ENV' $CI_ENV $OPENSHIFT_HOMEDIR/.env/user_vars  
fi

if [ ! -z "$OPENSHIFT_SECRET_TOKEN" ]; then
  export CI_KEY=${OPENSHIFT_SECRET_TOKEN:0:31}
  if [ "$(type -t set_env_var)" == "function" ]; then
    set_env_var 'CI_KEY' $CI_KEY $OPENSHIFT_HOMEDIR/.env/user_vars
  fi
fi

# If this is initial installation, create a cache directory
#
if [ ! -d ${OPENSHIFT_DATA_DIR}storage ]; then
  echo 1>&2
  echo "Creating storage directory..." 1>&2
  mkdir ${OPENSHIFT_DATA_DIR}storage
  mkdir ${OPENSHIFT_DATA_DIR}storage/app
  mkdir ${OPENSHIFT_DATA_DIR}storage/framework
  mkdir ${OPENSHIFT_DATA_DIR}storage/framework/cache
  mkdir ${OPENSHIFT_DATA_DIR}storage/framework/dbcache
fi
